db.url=jdbc:mysql://localhost:3306/db_pizapp?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
# Avec XAMPP local, utilisateur root et mot de passe vide par défaut
# Mettez vos propres valeurs si nécessaire
# Exemple: db.user=my_user
# Exemple: db.password=my_password
db.user=root
db.password=
